apiVersion: apps/v1
kind: Deployment
metadata:
  name: mohamed
spec: 
  selector:
    matchLabels:
      app: mohamed
  replicas: 3
  template:
    metadata:
      name : pods
      labels:
        app: mohamed
    spec: 
      containers:
        - image: momedetman/moh
          name: mohamed
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi "
